[0.0.8] Switch to automatic RubyGems publishing

diff --git a/.travis/publish b/.travis/publish
--- a/.travis/publish
+++ b/.travis/publish
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-if [ -z "$GITHUB_TOKEN" ]; then
-  echo "Error: must provide GITHUB_TOKEN" >&2
+if [ -z "$RUBYGEMS_API_KEY" ]; then
+  echo "Error: must provide RUBYGEMS_API_KEY" >&2
   exit 1
 fi
 
-echo ":github: Bearer $GITHUB_TOKEN" > $HOME/.gem/credentials
+echo ":rubygems_api_key: $RUBYGEMS_API_KEY" > $HOME/.gem/credentials
 chmod 0600 $HOME/.gem/credentials
-gem push --key github --host https://rubygems.pkg.github.com/joshk0 terraorg-*.gem
+gem push terraorg-*.gem
